---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubestronaut-predictor
  namespace: kubestronaut-predictor
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: github-credentials #k8s-open5gs
  timeout: 1m0s
  url: https://github.com/lfarizav/kubestronaut-predictor-deploy.git
