apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- monitoring-alert.yaml
- monitoring-helmrelease.yaml
- keda-alert.yaml
- keda-helmrelease.yaml
- monitoring-gitrepository.yaml


