apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: monitoring-deploy
  namespace: monitoring
spec:
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    name: monitoring
  providerRef:
    name: monitoring-deploy
